### ISSUE TITLE
Unit tests don't run when invoked as specified in SETUP.md

### ISSUE THREAD

**Issue by nebkor** [exercism/xracket#32]
I'm using Racket 6.2.1 on Linux, and as provided in the current master branch, the unit tests don't run when invoked like "racket hello-world-test.rkt", as of at least commit 1c53fe7fe61e15927b2555e2c15572b08586c6ca.

Here's what happens when you run the current test:
```
$:xracket/hello-world> racket hello-world-test.rkt
$:xracket/hello-world> 
```

However, it should fail at least one test.  If I change the "module+ test" on line 5 in hello-world-test.rkt to "begin", we get:
```
$:xracket/hello-world> racket hello-world-test.rkt
--------------------
hello world tests > with arg returns Hello, arg!
with arg returns Hello, arg!
FAILURE
name:       check-equal?
location:   hello-world-test.rkt:13:5
actual:     "hello, exercism!"
expected:   "Hello, exercism!"
Check failure
--------------------
1 success(es) 1 failure(s) 0 error(s) 2 test(s) run
1
```

Fixing the error also produces useful output:
```
$:xracket/hello-world> racket hello-world-test.rkt
2 success(es) 0 failure(s) 0 error(s) 2 test(s) run
0
```

I feel that I'm missing something fundamental; is there a way to invoke racket and tell it to use the local "test" module in the test file that I'm missing?

**Comment by nebkor** [comment]
Opened https://github.com/exercism/xracket/pull/33 to address this (I fixed the SETUP.md).

**Comment by nebkor** [comment]
The instructions for running the tests on http://help.exercism.io/getting-started-with-racket.html are also in need of the same change, but I don't know where that file lives.

**Comment by yurrriq** [comment]
[docs/TESTS.md](https://github.com/exercism/xracket/blob/master/docs/TESTS.md)

**Comment by kytrinyx** [comment]
We're getting rid of the `help.exercism.io` site (in the next few days). I've replaced this with language-specific pages on exercism.io: http://exercism.io/languages/racket
