### ISSUE TITLE
Word-count: tests reject mutable hashes

### ISSUE THREAD

**Issue by Bugfry** [exercism/xracket#39]
Hello all!

I came here from exercism to talk about the source of some confusion about the **word-count** problem in racket. It seems the tests fail if the returned hash is mutable. Neither in the README nor the test file is it mentioned, that the returned hashes should be immutable. The test's failure messages, e.g.:
```
--------------------
Tests for the word-count exercise > #f
Unnamed test 
FAILURE
name:       check-equal?
location:   word-count-test.rkt:37:5
actual:     '#hash(("for" . 1) ("wait" . 1) ("it" . 1))
expected:   '#hash(("it" . 1) ("wait" . 1) ("for" . 1))
message:    "multiple spaces"
Check failure
--------------------
```
are also not very helpful in finding the cause of the failure.

Is the behavior of the tests intentional?
If not, please fix the tests.
If yes, maybe you could make it more obvious what the tests are expecting?

**Comment by arguello** [comment]
Hi - thanks for catching that! I defined a custom hash check, which should fix that.
